name: build-and-publish-docker-image
on:
  push:
    branches:
      - master
    paths:
      - '**.go'
      - Dockerfile
      - .github/workflows/build-and-publish-docker-image.yaml
  pull_request:
    branches:
      - master
    paths:
      - '**.go'
      - Dockerfile
      - .github/workflows/build-and-publish-docker-image.yaml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MAJOR_VERSION: 0
  MiNOR_VERSION: 1

jobs:
  build-and-push:
    outputs:
      image_version: ${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{ github.run_number }}
    runs-on:
      - ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name:  Generate image tags
        id:    tag
        shell: bash
        run: |
          echo "Extracting branch tag from ${GITHUB_REF}"
          BRANCH=$(echo ${GITHUB_REF##*/} | tr -cd '[:alnum:]._-')
          echo "::set-output name=tag1::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{ github.run_number }}"
          echo "Setting tag1=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{ github.run_number }}"
          echo "::set-output name=tag2::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"
          echo "Setting tag2=${GITHUB_SHA}"
          if  [[ ( "${GITHUB_EVENT_NAME}" == "push" || "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ) && ( "${BRANCH}" == "master" || "${BRANCH}" == "main" ) ]]; then
            echo "::set-output name=tag3::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
            echo "Setting tag3=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          else
            echo "::set-output name=tag3::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop"
            echo "Setting tag3=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop"
          fi

       
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # version 1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # version 1.6.0

      - name: Log in to the Container registry
        uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583 # version 1.13.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      

      - name: Build and push Docker images
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b # version 2.9.0
        with:
          context: .
          push: true
          tags: "${{ steps.tag.outputs.tag1 }},${{ steps.tag.outputs.tag2 }},${{ steps.tag.outputs.tag3 }}"

 